/**
 * scripts/lib/snapshot-lib.mjs — pure functions that build the pieces of docs/SNAPSHOT.md
 * (T-017b, C3). scripts/snapshot.mjs just wires these together and writes/compares the file.
 */
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { gitIgnored, posix } from "./walk.mjs";
import { readEvents } from "./features.mjs";

const GENERATED_HEADER =
  "<!-- GENERATED by scripts/snapshot.mjs — DO NOT EDIT. Edit the sources listed in this " +
  "file's own header instead: ARCHITECTURE.md (§1, §4, §6), schema/*.schema.json, " +
  "docs/FEATURES.jsonl. -->";

/** Verbatim text of one `## N. Heading` section of ARCHITECTURE.md (heading line excluded). */
export function extractSection(architectureText, headingPrefix) {
  const lines = architectureText.split(/\r?\n/);
  const startIdx = lines.findIndex((l) => l.startsWith(headingPrefix));
  if (startIdx === -1) return "";
  const headingLine = lines[startIdx];
  let endIdx = lines.length;
  for (let i = startIdx + 1; i < lines.length; i++) {
    if (/^##\s/.test(lines[i])) {
      endIdx = i;
      break;
    }
  }
  return [headingLine, ...lines.slice(startIdx + 1, endIdx)].join("\n").trim();
}

/** `| Path | Owns | ... |` rows of ARCHITECTURE §4, as { path, owns } pairs. */
function ownsTableRows(section4Text) {
  const rows = [];
  for (const line of section4Text.split(/\r?\n/)) {
    const m = line.match(/^\|\s*(`[^`]+`(?:,\s*`[^`]+`)*)\s*\|\s*([^|]+)\|/);
    if (!m) continue;
    const owns = m[2].trim();
    for (const pathToken of m[1].matchAll(/`([^`]+)`/g)) {
      rows.push({ path: pathToken[1].replace(/\/\*?$/, ""), owns });
    }
  }
  return rows;
}

function packageDescription(root, relDir) {
  try {
    const pkg = JSON.parse(readFileSync(join(root, relDir, "package.json"), "utf8"));
    return pkg.description ?? null;
  } catch {
    return null;
  }
}

/**
 * Depth-2 directory tree under `root`, excluding `ignoreDirs` and gitignored paths. Each
 * top-level (depth-1) directory gets a one-line purpose: its package.json `description`, else
 * a matching row of ARCHITECTURE §4's `| Path | Owns |` table, else "".
 */
export function directoryTree(root, architectureSection4, ignoreDirs = []) {
  const skip = new Set([...ignoreDirs, ".git"]);
  const ownsRows = ownsTableRows(architectureSection4);
  const findOwns = (rel) => ownsRows.find((r) => r.path === rel || r.path === `${rel}/`)?.owns ?? "";

  const listDirs = (dir) => {
    let entries;
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return [];
    }
    return entries
      .filter((e) => e.isDirectory() && !skip.has(e.name) && !e.name.startsWith("."))
      .map((e) => e.name)
      .sort();
  };

  const top = listDirs(root);
  const topRel = top.map((name) => posix(name));
  const ignored = gitIgnored(root, topRel);

  const lines = [];
  for (const name of top) {
    const rel = posix(name);
    if (ignored.has(rel)) continue;
    const purpose = packageDescription(root, rel) ?? findOwns(rel);
    lines.push(`- \`${rel}/\`${purpose ? ` — ${purpose}` : ""}`);
    for (const child of listDirs(join(root, name))) {
      const childRel = posix(`${name}/${child}`);
      const childPurpose = packageDescription(root, childRel);
      lines.push(`  - \`${childRel}/\`${childPurpose ? ` — ${childPurpose}` : ""}`);
    }
  }
  return lines.join("\n");
}

/** One `| collection | required fields | evidence/provenance? |` row per schema/*.schema.json. */
export function schemaSummaryTable(schemaDir) {
  const files = readdirSync(schemaDir).filter((f) => f.endsWith(".schema.json")).sort();
  const rows = ["| Collection | Required fields | Evidence/provenance field |", "|---|---|---|"];
  for (const f of files) {
    const schema = JSON.parse(readFileSync(join(schemaDir, f), "utf8"));
    const collection = f.replace(/\.schema\.json$/, "");
    const required = (schema.required ?? []).join(", ");
    const propNames = Object.keys(schema.properties ?? {});
    const hasEvidence = propNames.some((p) => /evidence|provenance/i.test(p)) ? "yes" : "no";
    rows.push(`| ${collection} | ${required} | ${hasEvidence} |`);
  }
  return rows.join("\n");
}

/** Last `n` rows of docs/FEATURES.jsonl as a markdown table (empty-ledger safe). */
export function featuresTail(ledgerPath, n = 20) {
  const events = readEvents(ledgerPath);
  const tail = events.slice(-n);
  const rows = ["| Date | Feature | Event | Reason |", "|---|---|---|---|"];
  for (const e of tail) {
    rows.push(`| ${e.date} | ${e.feature} | ${e.event} | ${e.reason ?? "—"} |`);
  }
  return rows.join("\n") + "\n\nfull history: `docs/FEATURES.jsonl`";
}

/** Assembles the full docs/SNAPSHOT.md content from an already-read ARCHITECTURE.md text. */
export function buildSnapshot({ root, architectureText, schemaDir, ledgerPath, ignoreDirs }) {
  const section1 = extractSection(architectureText, "## 1.");
  const section4 = extractSection(architectureText, "## 4.");
  const section6 = extractSection(architectureText, "## 6.");
  const parts = [
    GENERATED_HEADER,
    "",
    "# SNAPSHOT",
    "",
    section1,
    "",
    "## Directory tree (depth 2)",
    "",
    directoryTree(root, section4, ignoreDirs),
    "",
    "## Schema summary",
    "",
    schemaSummaryTable(schemaDir),
    "",
    "## Recent feature events (last 20)",
    "",
    featuresTail(ledgerPath, 20),
    "",
    section6,
    "",
  ];
  return parts.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\s+$/, "\n");
}

export { GENERATED_HEADER };
