#!/usr/bin/env node
/**
 * scripts/catalogue-score.mjs — generates docs/PROGRESS.md, the honest answer to
 * "how much of the product actually exists?" (plan §10 U0.5).
 *
 * It exists because `.goal/goal.json` reported **79%** while the real figure against the product
 * catalogue was closer to a quarter: that number measured 29 foundation tasks, not the 57-feature
 * product, so it answered a much easier question than the one people were reading it as.
 *
 * Verdicts here are DERIVED from four machine signals (see scripts/lib/catalogue.mjs) — live route
 * table, real collection counts from the newest live-verify evidence, real SPA routes, and package
 * reachability. A human may only ever LOWER a derived verdict, with a reason recorded in
 * `.goal/catalogue.json`; an attempted upgrade fails the run. Both the auto-derived and the
 * human-adjusted score are printed, so how much rests on judgement is always visible.
 *
 * Usage:
 *   node scripts/catalogue-score.mjs           — write docs/PROGRESS.md
 *   node scripts/catalogue-score.mjs --check   — exit 1 if the committed file is stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  scrapeRoutes, scrapePages, reachablePackages, scoreCatalogue, GROUP_NAMES, createRecordingReader,
  assertDenominator, scaleDescription,
} from "./lib/catalogue.mjs";
import { loadCollectionCounts, trustOf, isTrustworthy, trustWarning, untrustedAmong } from "./lib/evidence.mjs";

/**
 * Every score-raising INPUT gets the same trust check.
 *
 * This was a hand-maintained list of one path, and the checker's answer was correct: that is not
 * acceptable, because "which files did this program read" is a fact the program already knows —
 * and the list was already wrong by three surfaces. The route/page/package scrapers read source
 * code as text with no trust check, so uncommitted source edits bought +10.5 points with every
 * gate green and no banner (ISS-047). Worse than an attack, it was a live hazard: anyone on a
 * feature branch running `pnpm progress` would commit a score measuring their working tree rather
 * than the repository.
 *
 * So the set is now DERIVED — the scrapers read through a recording reader, and whatever they
 * actually touched gets trust-checked. Only `.goal/catalogue.json` is named explicitly, because it
 * is parsed rather than read through a scraper.
 */
const EXPLICIT_INPUTS = [".goal/catalogue.json"];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "PROGRESS.md");

export function generate(root = ROOT) {
  const catalogue = JSON.parse(readFileSync(join(root, ".goal", "catalogue.json"), "utf8"));
  assertDenominator(catalogue); // dropping features is the cheapest way to inflate a percentage
  const { counts, source, stamp, hash, trusted, warning, trust, unreadable } = loadCollectionCounts(root);
  // Read every source signal through a recorder, so the trust check below covers exactly what was
  // read rather than what someone remembered to list (ISS-047).
  const reader = createRecordingReader(root);
  const signals = {
    routes: scrapeRoutes(root, reader.read),
    counts,
    pages: scrapePages(root, reader.read),
    packages: reachablePackages(root, reader.read),
  };
  const s = scoreCatalogue(catalogue, signals);
  s.evidence = counts ? { source, stamp, hash, trusted, warning, trust } : null;
  s.inputs = EXPLICIT_INPUTS.map((rel) => {
    const t = trustOf(root, rel);
    return { source: rel, trust: t, trusted: isTrustworthy(t), warning: trustWarning(t, rel) };
  });
  // …plus every file the scrapers actually read. One `git status` call answers for all of them;
  // per-path `git diff` would be hundreds of processes.
  const scraped = [...reader.files];
  s.scrapedCount = scraped.length;
  s.scrapedFiles = scraped; // exposed so a test can assert the trusted set covers what was read
  for (const [rel, t] of untrustedAmong(root, scraped)) {
    s.inputs.push({ source: rel, trust: t, trusted: false, warning: trustWarning(t, rel) });
  }

  const bar = (pct) => "█".repeat(Math.round(pct / 5)).padEnd(20, "░");
  const L = [
    "<!-- GENERATED by scripts/catalogue-score.mjs — DO NOT EDIT.",
    "     Edit .goal/catalogue.json (probes / manual downgrades), then re-run. -->",
    "# Progress — what actually exists",
    "",
    `**${s.adjustedPercent}% of the ${s.total}-feature product catalogue.**`,
    `Machine-derived alone: ${s.autoPercent}%. Scoring: ${scaleDescription()}.`,
    "",
    `Denominator pinned to plan §4c (${s.total} features; dropping one fails the run). Probe fingerprint \`${s.probeHash}\` —`,
    `if that changes, a probe was edited and the score is not comparable to the previous run.`,
    `${s.probeless.length} feature(s) declare no probe and therefore score MISSING by default: ${s.probeless.join(", ")}.`,
    ...s.inputs.filter((i) => i.warning).map((i) => `\n> ${i.warning}`),
    ...unreadable.map((u) => `\n> **UNREADABLE EVIDENCE — \`${u.rel}\` could not be parsed (${u.reason}) — it was skipped, not counted as absent. Fix or delete it.**`),
    "",
    counts
      ? `Collection counts from \`${source}\` (run ${stamp}, content \`${hash}\`)${warning ? ` — ${warning}` : ""}. Chosen by the timestamp inside the file, not by folder name. Re-run \`pnpm verify:live\` for fresher numbers.`
      : "> **No live-verify evidence found** — every collection probe is unresolved, so this score is a floor, not a measurement. Run `pnpm verify:live`.",
    "",
    "## By group",
    "",
    "| group | | score | REAL | PARTIAL | STUB | MISSING |",
    "|---|---|---|---|---|---|---|",
  ];
  for (const g of Object.keys(GROUP_NAMES)) {
    const b = s.byGroup[g];
    if (!b) continue;
    const pct = Math.round((b.adjusted / b.total) * 1000) / 10;
    const c = b.counts;
    L.push(`| **${g}. ${GROUP_NAMES[g]}** | \`${bar(pct)}\` | ${pct}% | ${c.REAL ?? 0} | ${c.PARTIAL ?? 0} | ${c.STUB ?? 0} | ${c.MISSING ?? 0} |`);
  }

  L.push("", "## Every feature", "", "| id | feature | verdict | derived from |", "|---|---|---|---|");
  for (const r of s.rows) {
    const why = r.passed.length > 0 ? r.passed.join("; ") : (r.failed[0] ?? "no probe declared");
    const flag = r.verdict !== r.auto ? ` _(auto: ${r.auto}, lowered)_` : "";
    L.push(`| ${r.id} | ${r.name} | **${r.verdict}**${flag} | ${why} |`);
  }

  const lowered = s.rows.filter((r) => r.verdict !== r.auto);
  if (lowered.length > 0) {
    L.push("", "## Human downgrades (machine said better; a person said otherwise)", "");
    for (const r of lowered) L.push(`- **${r.id}** ${r.auto} → ${r.verdict} — ${r.manual.reason}`);
  }
  const noted = s.rows.filter((r) => r.note);
  if (noted.length > 0) {
    L.push("", "## Notes (context that does NOT change a verdict)", "");
    for (const r of noted) L.push(`- **${r.id}** (${r.verdict}) — ${r.note}`);
  }
  L.push("");
  return { text: L.join("\n"), score: s };
}

function main(argv) {
  let text, score;
  try {
    ({ text, score } = generate());
  } catch (err) {
    // A dropped/renamed feature is a deliberate refusal, not a crash — say so in one line rather
    // than dumping a stack trace at someone who just edited a JSON file.
    console.error(`REFUSED: ${err.message}`);
    process.exit(2);
  }
  if (score.upgrades.length > 0) {
    console.error("REFUSED: .goal/catalogue.json tries to UPGRADE a derived verdict:");
    for (const u of score.upgrades) console.error(`  ${u}`);
    console.error("A manual entry may only lower a verdict — otherwise the score is self-assessment.");
    process.exit(2);
  }
  if (argv.includes("--check")) {
    // `--check` is the gate in `pnpm lint:structure`, so it holds the stricter line: a score
    // computed from evidence nobody else has is not a shared fact. Write mode still allows
    // uncommitted evidence (with the loud banner) so local iteration is not blocked — but the
    // gate everyone trusts cannot pass on a file that exists only on one machine (ISS-035).
    const untrusted = [
      ...(score.evidence && !score.evidence.trusted ? [score.evidence] : []),
      ...score.inputs.filter((i) => !i.trusted),
    ];
    if (untrusted.length > 0) {
      for (const u of untrusted) {
        console.error(`REFUSED: ${u.source} is not what the repository holds (${u.trust}). Commit it, or restore it, so the score is reproducible by someone else.`);
      }
      process.exit(2);
    }
    // Compare line-ending-insensitively: under `core.autocrlf=true` the committed file
    // materialises with CRLF while generation emits LF, which sent `--check` STALE on an
    // untouched clone — a staleness gate that cries wolf on a fresh checkout gets ignored,
    // and then catches nothing (ISS-043).
    const lf = (t) => t.replace(/\r\n/g, "\n");
    const committed = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (lf(committed) !== lf(text)) {
      console.error("STALE: docs/PROGRESS.md differs from a fresh regeneration. Run: node scripts/catalogue-score.mjs");
      process.exit(1);
    }
    console.log(`OK: docs/PROGRESS.md is current (${score.adjustedPercent}% of ${score.total} features)`);
    return;
  }
  writeFileSync(OUT, text);
  console.log(`wrote docs/PROGRESS.md — ${score.adjustedPercent}% adjusted / ${score.autoPercent}% machine-derived, ${score.total} features`);
}

// `pathToFileURL`, not a hand-built file:// string — hand-building drops the leading slash that
// Windows absolute paths need, so the guard silently never fires (real bug, apps/api/src/index.ts:21).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2));
}
