#!/usr/bin/env node
/**
 * scripts/catalogue-score.mjs — generates docs/PROGRESS.md, the honest answer to
 * "how much of the product actually exists?" (plan §10 U0.5).
 *
 * It exists because `.goal/goal.json` reported **79%** while the real figure against the product
 * catalogue was closer to a quarter: that number measured 29 foundation tasks, not the 57-feature
 * product, so it answered a much easier question than the one people were reading it as.
 *
 * Verdicts here are DERIVED from four machine signals (see scripts/lib/catalogue.mjs) — live route
 * table, real collection counts from the newest live-verify evidence, real SPA routes, and package
 * reachability. A human may only ever LOWER a derived verdict, with a reason recorded in
 * `.goal/catalogue.json`; an attempted upgrade fails the run. Both the auto-derived and the
 * human-adjusted score are printed, so how much rests on judgement is always visible.
 *
 * Usage:
 *   node scripts/catalogue-score.mjs           — write docs/PROGRESS.md
 *   node scripts/catalogue-score.mjs --check   — exit 1 if the committed file is stale
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import {
  scrapeRoutes, loadCollectionCounts, scrapePages, reachablePackages, scoreCatalogue, GROUP_NAMES,
  assertDenominator,
} from "./lib/catalogue.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "PROGRESS.md");

export function generate(root = ROOT) {
  const catalogue = JSON.parse(readFileSync(join(root, ".goal", "catalogue.json"), "utf8"));
  assertDenominator(catalogue); // dropping features is the cheapest way to inflate a percentage
  const { counts, source } = loadCollectionCounts(root);
  const signals = {
    routes: scrapeRoutes(root),
    counts,
    pages: scrapePages(root),
    packages: reachablePackages(root),
  };
  const s = scoreCatalogue(catalogue, signals);

  const bar = (pct) => "█".repeat(Math.round(pct / 5)).padEnd(20, "░");
  const L = [
    "<!-- GENERATED by scripts/catalogue-score.mjs — DO NOT EDIT.",
    "     Edit .goal/catalogue.json (probes / manual downgrades), then re-run. -->",
    "# Progress — what actually exists",
    "",
    `**${s.adjustedPercent}% of the ${s.total}-feature product catalogue.**`,
    `Machine-derived alone: ${s.autoPercent}%. Scoring: REAL=1, PARTIAL=0.5, STUB/MISSING=0.`,
    "",
    `Denominator pinned to plan §4c (${s.total} features; dropping one fails the run). Probe fingerprint \`${s.probeHash}\` —`,
    `if that changes, a probe was edited and the score is not comparable to the previous run.`,
    `${s.probeless.length} feature(s) declare no probe and therefore score MISSING by default: ${s.probeless.join(", ")}.`,
    "",
    counts
      ? `Collection counts read from \`${source}\`. Re-run \`pnpm verify:live\` first for fresher numbers.`
      : "> **No live-verify evidence found** — every collection probe is unresolved, so this score is a floor, not a measurement. Run `pnpm verify:live`.",
    "",
    "## By group",
    "",
    "| group | | score | REAL | PARTIAL | STUB | MISSING |",
    "|---|---|---|---|---|---|---|",
  ];
  for (const g of Object.keys(GROUP_NAMES)) {
    const b = s.byGroup[g];
    if (!b) continue;
    const pct = Math.round((b.adjusted / b.total) * 1000) / 10;
    const c = b.counts;
    L.push(`| **${g}. ${GROUP_NAMES[g]}** | \`${bar(pct)}\` | ${pct}% | ${c.REAL ?? 0} | ${c.PARTIAL ?? 0} | ${c.STUB ?? 0} | ${c.MISSING ?? 0} |`);
  }

  L.push("", "## Every feature", "", "| id | feature | verdict | derived from |", "|---|---|---|---|");
  for (const r of s.rows) {
    const why = r.passed.length > 0 ? r.passed.join("; ") : (r.failed[0] ?? "no probe declared");
    const flag = r.verdict !== r.auto ? ` _(auto: ${r.auto}, lowered)_` : "";
    L.push(`| ${r.id} | ${r.name} | **${r.verdict}**${flag} | ${why} |`);
  }

  const lowered = s.rows.filter((r) => r.verdict !== r.auto);
  if (lowered.length > 0) {
    L.push("", "## Human downgrades (machine said better; a person said otherwise)", "");
    for (const r of lowered) L.push(`- **${r.id}** ${r.auto} → ${r.verdict} — ${r.manual.reason}`);
  }
  const noted = s.rows.filter((r) => r.note);
  if (noted.length > 0) {
    L.push("", "## Notes (context that does NOT change a verdict)", "");
    for (const r of noted) L.push(`- **${r.id}** (${r.verdict}) — ${r.note}`);
  }
  L.push("");
  return { text: L.join("\n"), score: s };
}

function main(argv) {
  let text, score;
  try {
    ({ text, score } = generate());
  } catch (err) {
    // A dropped/renamed feature is a deliberate refusal, not a crash — say so in one line rather
    // than dumping a stack trace at someone who just edited a JSON file.
    console.error(`REFUSED: ${err.message}`);
    process.exit(2);
  }
  if (score.upgrades.length > 0) {
    console.error("REFUSED: .goal/catalogue.json tries to UPGRADE a derived verdict:");
    for (const u of score.upgrades) console.error(`  ${u}`);
    console.error("A manual entry may only lower a verdict — otherwise the score is self-assessment.");
    process.exit(2);
  }
  if (argv.includes("--check")) {
    const committed = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (committed !== text) {
      console.error("STALE: docs/PROGRESS.md differs from a fresh regeneration. Run: node scripts/catalogue-score.mjs");
      process.exit(1);
    }
    console.log(`OK: docs/PROGRESS.md is current (${score.adjustedPercent}% of ${score.total} features)`);
    return;
  }
  writeFileSync(OUT, text);
  console.log(`wrote docs/PROGRESS.md — ${score.adjustedPercent}% adjusted / ${score.autoPercent}% machine-derived, ${score.total} features`);
}

// `pathToFileURL`, not a hand-built file:// string — hand-building drops the leading slash that
// Windows absolute paths need, so the guard silently never fires (real bug, apps/api/src/index.ts:21).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2));
}
