#!/usr/bin/env node
/**
 * scripts/live-verify.mjs — the REPRODUCIBLE half of the plan §9 Phase-0 validation protocol.
 *
 * Writes a dated evidence folder (`qa/evidence/live-<date>/`) containing, for one run:
 *   preflight.json  — git HEAD + working-tree cleanliness, listening ports, and a real
 *                     `countDocuments` for EVERY collection in `schema/` (this is what turns
 *                     "that collection is empty" from an opinion into an on-disk fact)
 *   api/<route>.json— the raw response body of every read route, exactly as the server sent it
 *   summary.md      — the verdict per check
 *
 * Why it exists: a claim that cannot be regenerated by re-running one command does not count.
 * The browser half of the protocol (headed Playwright walk + `pnpm demo:live`) reconciles what
 * is on screen against these exact bytes — a screenshot alone is not evidence.
 *
 * It NEVER writes application content: no seeding, no tree rebuild, no ingest. The only write
 * anywhere in the protocol is minting a credential (`scripts/mint-key.mjs`), deliberately kept
 * in its own script. `POST /ask` is exercised because it is the product's core path; it causes
 * the server to append `jobs` ledger rows, and this script MEASURES that delta rather than
 * asserting a figure for it. `--skip-ask` opts out.
 *
 * Verdict vocabulary: PASS · FAIL · STUB (deliberate 501) · MISSING (route absent) ·
 * INCONCLUSIVE (the remote Mongo is genuinely flaky — a timeout must never be read as a FAIL) ·
 * DIRTY-TREE (the run is valid, but its evidence cannot be attributed to the current commit).
 *
 * Usage:
 *   node scripts/mint-key.mjs                 # once, prints a key
 *   LKB_API_KEY=<key> node scripts/live-verify.mjs [--api http://localhost:3300] [--skip-ask]
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import "dotenv/config";
import { register } from "tsx/esm/api";

register();

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const argOf = (n, d) => {
  const i = process.argv.indexOf(`--${n}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : d;
};
const API = argOf("api", "http://localhost:3300");
const WEB = argOf("web", "http://localhost:5173");
const KEY = argOf("key", process.env.LKB_API_KEY ?? "");
const SKIP_ASK = process.argv.includes("--skip-ask");
const STAMP = new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
const OUT = resolve(ROOT, argOf("out", join("qa", "evidence", `live-${STAMP}`)));

const checks = [];
let askJobsDelta = null; // measured, never assumed — see the /ask block below
const record = (name, verdict, detail) => {
  checks.push({ name, verdict, detail });
  console.log(`[${verdict.padEnd(12)}] ${name}${detail ? ` — ${detail}` : ""}`);
};

mkdirSync(join(OUT, "api"), { recursive: true });

// ---------------------------------------------------------------- layer 0: preflight
// execFile, not exec: no shell, so nothing here can ever be turned into a shell string.
const git = (...args) => {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
};

const head = git("rev-parse", "HEAD");
// The tool's own output is not source: `qa/evidence/` is excluded so a run cannot dirty the tree
// it is measuring and make the NEXT run report a worse attribution than it deserves (ISS-027).
const dirty = git("status", "--porcelain")
  .split("\n")
  .map((l) => l.trim())
  .filter((l) => l && !/\s+qa\/evidence\//.test(` ${l}`));
const preflight = {
  stamp: new Date().toISOString(),
  gitHead: head,
  workingTreeClean: dirty.length === 0,
  dirtyFiles: dirty,
  api: API,
  web: WEB,
  mongoUrl: (process.env.MONGODB_URL ?? "").replace(/\/\/[^@]*@/, "//<redacted>@"),
  collections: {},
  collectionsError: null,
};

// A dirty tree is NOT a failure of the system under test — it is a caveat on the evidence: the
// result cannot be attributed to `gitHead` alone. Its own verdict, so that (a) an in-flight run
// is not misreported as a broken app, and (b) nobody can hide a real failure behind it, since
// every other check still stands or falls on its own.
record(
  "preflight: evidence attributable to a commit",
  preflight.workingTreeClean ? "PASS" : "DIRTY-TREE",
  preflight.workingTreeClean
    ? head.slice(0, 8)
    : `${preflight.dirtyFiles.length} uncommitted file(s) — not reproducible from ${head.slice(0, 8)} alone; not valid as final acceptance evidence for a shipped commit`,
);

// Real per-collection counts, driven off schema/ so a newly added collection is never silently
// left unmeasured.
const collectionNames = readdirSync(join(ROOT, "schema"))
  .filter((f) => f.endsWith(".schema.json"))
  .map((f) => f.replace(".schema.json", ""))
  .sort();

let mongoOk = false;
try {
  const { connect, getDb } = await import("../packages/db/src/index.ts");
  const url = process.env.MONGODB_URL;
  if (!url) throw new Error("MONGODB_URL not set");
  await connect(url, process.env.MONGODB_DB ?? "lkb");
  const db = getDb();
  for (const name of collectionNames) {
    preflight.collections[name] = await db.collection(name).countDocuments();
  }
  mongoOk = true;
  const populated = collectionNames.filter((c) => preflight.collections[c] > 0);
  record(
    "preflight: mongo collection counts",
    "PASS",
    `${populated.length}/${collectionNames.length} collection(s) have ≥1 real document`,
  );
} catch (err) {
  preflight.collectionsError = String(err?.message ?? err);
  record("preflight: mongo collection counts", "INCONCLUSIVE", preflight.collectionsError);
}

writeFileSync(join(OUT, "preflight.json"), `${JSON.stringify(preflight, null, 2)}\n`);

// ---------------------------------------------------------------- layer 1: API truth pass
const slug = (p) => p.replace(/^\//, "").replace(/[/?:]/g, "_") || "root";

async function hit(method, path, { expect = 200, body, scope } = {}) {
  const name = `${method} ${path}${scope ? ` (scope: ${scope})` : ""}`;
  let res;
  try {
    res = await fetch(`${API}${path}`, {
      method,
      headers: {
        ...(KEY ? { Authorization: `Bearer ${KEY}` } : {}),
        ...(body ? { "Content-Type": "application/json" } : {}),
      },
      ...(body ? { body: JSON.stringify(body) } : {}),
    });
  } catch (err) {
    record(name, "INCONCLUSIVE", `server unreachable: ${String(err?.message ?? err)}`);
    return null;
  }
  const text = await res.text();
  writeFileSync(join(OUT, "api", `${method}_${slug(path)}.json`), text);
  let parsed = null;
  try {
    parsed = JSON.parse(text);
  } catch {
    /* non-JSON body is itself evidence; it is already on disk */
  }
  // A deliberate 501/404 is a recorded product fact (STUB/MISSING), never a failed check.
  //
  // These are "not-worse-than" assertions, not equality assertions (ISS-027 -> ISS-026): a stub
  // that has since been IMPLEMENTED must not turn the suite red. Whoever finally builds
  // `GET /search` should get a green run that tells them to promote the check — penalising
  // progress is how a verification suite gets ignored.
  let verdict;
  let note = "";
  if (res.status === expect) {
    verdict = expect === 501 ? "STUB" : expect === 404 ? "MISSING" : "PASS";
  } else if (expect !== 200 && res.ok) {
    verdict = "PASS";
    note = ` — was ${expect}, now implemented: promote this to a real check`;
  } else {
    verdict = "FAIL";
    note = ` (expected ${expect})`;
  }
  record(name, verdict, `HTTP ${res.status}${note}`);
  return parsed;
}

if (!KEY) {
  record("api: credential", "INCONCLUSIVE", "no LKB_API_KEY / --key — run `node scripts/mint-key.mjs` first");
} else {
  const sessions = await hit("GET", "/sessions", { scope: "sessions" });
  await hit("GET", "/sources", { scope: "sources" });
  await hit("GET", "/gaps", { scope: "gaps" });
  await hit("GET", "/graph", { scope: "graph" });
  await hit("GET", "/calendar/upcoming", { scope: "calendar" });
  await hit("GET", "/meeting-candidates", { scope: "gmail" });
  await hit("GET", "/whatsapp/groups", { scope: "whatsapp" });
  await hit("GET", "/keys", { scope: "keys" });
  await hit("GET", "/search", { scope: "search", expect: 501 });
  await hit("GET", "/citations/none", { scope: "citations", expect: 501 });
  await hit("GET", "/health", { expect: 404 });

  // Reconcile the list route against the raw Mongo count — the check that makes a UI screenshot
  // meaningful later, because both must agree with this same number.
  const listed = Array.isArray(sessions?.sessions) ? sessions.sessions.length : null;
  if (listed !== null && mongoOk) {
    const inMongo = preflight.collections.sessions;
    record(
      "reconcile: GET /sessions length == sessions in Mongo",
      listed === inMongo ? "PASS" : "FAIL",
      `api=${listed} mongo=${inMongo}`,
    );
    const first = sessions.sessions[0]?._id;
    if (first) await hit("GET", `/sessions/${encodeURIComponent(first)}`, { scope: "sessions" });
  } else if (listed === null) {
    record("reconcile: GET /sessions length == sessions in Mongo", "INCONCLUSIVE", "no session list to compare");
  }

  if (!SKIP_ASK) {
    // Measure this run's own side effect instead of asserting a constant for it. The first
    // version of this file claimed `/ask` "appends one real jobs ledger row"; the real figure is
    // 20-30 and non-deterministic (one row per evaluator/score call), and that false constant was
    // being written into every evidence artifact — an unmeasured claim inside the very tool built
    // to eliminate unmeasured claims (ISS-024, checker, 2026-09-07).
    const jobsBefore = mongoOk ? await (await import("../packages/db/src/index.ts")).getDb().collection("jobs").countDocuments() : null;
    const ask = await hit("POST", "/ask", { scope: "ask", body: { query: "What did speakers say about student visas?" } });
    if (mongoOk) {
      const { getDb } = await import("../packages/db/src/index.ts");
      askJobsDelta = (await getDb().collection("jobs").countDocuments()) - jobsBefore;
      record("POST /ask side effect measured", "PASS", `appended ${askJobsDelta} real \`jobs\` ledger row(s)`);
    }
    // The product's whole promise is a cited answer: an answer with no citation is a real FAIL,
    // not a soft warning. `sources` is `{internal: [...], web: [...]}` (askV2's real shape — the
    // first version of this check assumed a flat array and produced a FALSE FAIL against a
    // perfectly good answer, 2026-09-07; assert against the shape the server actually sends).
    if (ask) {
      const internal = ask.sources?.internal ?? [];
      const web = ask.sources?.web ?? [];
      const n = internal.length + web.length;
      record(
        "POST /ask returns at least one citation",
        n > 0 ? "PASS" : "FAIL",
        `${internal.length} internal + ${web.length} web · verdict=${ask.verdict}`,
      );
      // Every cited internal node must resolve to a session that really exists in Mongo —
      // this is what separates a real citation from a plausible-looking hallucinated id.
      // EVERY cited source must yield a ref, not just the subset that happened to have one:
      // otherwise a response whose sources all lack `evidence.sessionRef` gives refs=[] and
      // 0 === 0 records a vacuous PASS (ISS-025, checker, 2026-09-07).
      if (mongoOk && internal.length > 0) {
        const { getDb } = await import("../packages/db/src/index.ts");
        const refs = [...new Set(internal.map((s) => s.evidence?.sessionRef).filter(Boolean))];
        const unref = internal.length - internal.filter((s) => s.evidence?.sessionRef).length;
        const found = refs.length === 0 ? -1 : await getDb().collection("sessions").countDocuments({ _id: { $in: refs } });
        record(
          "POST /ask citations resolve to real sessions",
          unref === 0 && refs.length > 0 && found === refs.length ? "PASS" : "FAIL",
          unref > 0
            ? `${unref}/${internal.length} cited source(s) carried no evidence.sessionRef — unverifiable`
            : `${found}/${refs.length} cited sessionRef(s) exist in Mongo`,
        );
      }
    }
  }
}

// ---------------------------------------------------------------- report
const tally = checks.reduce((acc, c) => ({ ...acc, [c.verdict]: (acc[c.verdict] ?? 0) + 1 }), {});
const overall = checks.some((c) => c.verdict === "FAIL")
  ? "FAIL"
  : checks.some((c) => c.verdict === "INCONCLUSIVE")
    ? "INCONCLUSIVE"
    : "PASS";

// The headline carries the attribution caveat, so a machine consumer sees what the prose says.
const headline = `${overall}${preflight.workingTreeClean ? "" : ` (DIRTY-TREE — not attributable to ${head.slice(0, 8)})`}`;

const lines = [
  `# live-verify — ${preflight.stamp}`,
  "",
  `**Overall: ${headline}** · ${Object.entries(tally).map(([k, v]) => `${k}: ${v}`).join(" · ")}`,
  "",
  `- commit: \`${head}\`${preflight.workingTreeClean ? "" : " — **working tree DIRTY**, so this run is not valid as final acceptance evidence for this commit"}`,
  `- api: ${API} · web: ${WEB}`,
  `- \`POST /ask\` ${SKIP_ASK ? "skipped (--skip-ask)" : `exercised — appended ${askJobsDelta ?? "an unmeasured number of"} real \`jobs\` ledger row(s) this run (measured, not assumed)`}`,
  "",
  "## Checks",
  "",
  "| verdict | check | detail |",
  "|---|---|---|",
  ...checks.map((c) => `| ${c.verdict} | ${c.name} | ${c.detail ?? ""} |`),
  "",
  "## Collection counts (real `countDocuments`)",
  "",
  mongoOk ? "| collection | documents |\n|---|---|" : `_unavailable: ${preflight.collectionsError}_`,
  ...(mongoOk ? collectionNames.map((c) => `| ${c} | ${preflight.collections[c]} |`) : []),
  "",
  "## Not exercised (write paths, deliberately)",
  "",
  "`POST /ingest` · `POST /whatsapp/ingest` · `POST /compete/*` · `POST /gmail/scan` ·",
  "`POST /keys` · `DELETE /keys/:id` · `POST /webhooks/register` — this run never mutates",
  "application content, so these are reported as uncovered rather than silently skipped.",
  "",
  "## Browser half (not automatable away)",
  "",
  `Run \`pnpm demo:live\` and click through: ${WEB}/ · /sessions · /brain · /calendar · /sources ·`,
  "/ingest · /whatsapp · /meeting-bot · /settings. Each page's numbers must reconcile against the",
  "collection counts above and the raw bodies in `api/`.",
  "",
];
writeFileSync(join(OUT, "summary.md"), lines.join("\n"));

console.log(`\noverall: ${headline}\nevidence: ${OUT}`);
// Exit codes: 0 PASS · 2 FAIL · 3 INCONCLUSIVE · 4 PASS-but-DIRTY-TREE. 4 exists so a machine
// consumer can tell attributable evidence from non-attributable evidence, which the human-readable
// line already distinguished but the exit code previously flattened to 0 (ISS-027).
process.exit(
  overall === "FAIL" ? 2 : overall === "INCONCLUSIVE" ? 3 : preflight.workingTreeClean ? 0 : 4,
);
